[theme]
primaryColor = "#0077B6"
backgroundColor = "#FFFFFF"
secondaryBackgroundColor = "#CAF0F8"
textColor = "#03045E"
font = "sans serif"

[browser]
gatherUsageStats = false

[server]
headless = true
